### ISSUE TITLE
Getting java.net.MalformedURLException: in runMethod()

### ISSUE THREAD

**Issue by naeem-github** [alexandersjn/btc_e_assist_api#4]
Getting MalformedURLException while executing ta.depth.runMethod();

Error Log:
java.net.MalformedURLException: no protocol: null/api/3/depth/bch_usd-?limit=100&ignore_invalid=1
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at com.assist.PublicBaseClass.sendRequest(PublicBaseClass.java:114)
	at com.assist.Depth.runMethod(Depth.java:14)
	at com.info.Information.getOrderBook(Information.java:23)
	at com.info.Information.main(Information.java:10)

**Comment by alexandersjn** [comment]
Hi!
Address is wrong: null/api/3/depth, it should be like http://wex.nz/api/3/depth. May be you can't connect to the wex.nz ?

**Comment by naeem-github** [comment]
yeah, maybe that is an issue.
closing now.
